include: package:lint/analysis_options.yaml

analyzer:
  errors:
    constant_identifier_names: ignore
    avoid_private_typedef_functions: info
    missing_enum_constant_in_switch: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    avoid_print: error
  exclude:
    - "**/*.g.dart"
    - "**/*.framy.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
